VSchool/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VSchool.Models;
using VSchool.ModelView;


namespace VSchool.Controllers
{
    public class StudentController : Controller
    {
        TestEntities db = new TestEntities();
        // GET: Student
        public ActionResult Index()
        {
           // List<Student> students = db.Students.ToList();
            return View();
        }

        public ActionResult SearchStudent (string  searchName, string searchEmail)
        {

            //List<Student> students = db.Students.Where(std => (std.Name.Contains(searchName) || (std.Name == null||std.Name=="")) &&
            //(std.Email.Contains(searchEmail) || (std.Email == null || std.Name==""))).ToList();

            List<Student> students = db.Students.Where(student => (student.Name.Contains(searchName) || searchName == null ||searchName=="") && (student.Email.Contains(searchEmail) || searchEmail == null || searchEmail == "")).ToList();

            return View(students);
        }

        public ActionResult Create()
        {
            ViewBag.genderId = new SelectList(db.Genders.ToList(), "Id", "Name","Select Gender");
            return View();
        }

        [HttpPost]
        public ActionResult Create(StudentViewModel passedStudent)
        {
            Student student = new Student();
            student.Name = passedStudent.Name;
            student.Email = passedStudent.Email;
            student.Genderd = passedStudent.Genderd;
            
            //Uploading Image for student
            //File Attatchments
            if (passedStudent.studentImage != null)
            {
                if (!Directory.Exists(Server.MapPath("~/UploadFiles/StudentImage/")))
                {
                    Directory.CreateDirectory(Server.MapPath("~/UploadFiles/StudentImage/"));
                }

                string attachmentNumber = Guid.NewGuid().ToString();
                string InputFileName = Path.GetFileNameWithoutExtension(passedStudent.studentImage.FileName);
                //if (InputFileName.Length > 30)
                //{
                //    InputFileName = InputFileName.Substring(0, 30);
                //}

                var InputExtension = Path.GetExtension(passedStudent.studentImage.FileName);


                var ServerSavePath = Path.Combine(Server.MapPath("~/UploadFiles/StudentImage/") + attachmentNumber + InputFileName + InputExtension);

                // save attachment in folder
                passedStudent.studentImage.SaveAs(ServerSavePath);
                student.Photo = attachmentNumber + InputFileName + InputExtension;
            }

            db.Students.Add(student);
            db.SaveChanges();

            return RedirectToAction("Index");
        }


        public ActionResult Edit(int id)
        {
           
            StudentViewModel oldStudent = db.Students.Where(st => st.Id == id).Select(std => new StudentViewModel
            {
                
                Name = std.Name,
                Email = std.Email,
                Photo = std.Photo,
                Genderd = std.Genderd,
                
            }).FirstOrDefault();
            ViewBag.genderId = new SelectList(db.Genders.ToList(), "Id", "Name",id);
            return View(oldStudent);

        }

        [HttpPost]
        public ActionResult Edit(StudentViewModel passedStudent)
        {
            Student student = db.Students.Where(std => std.Id == passedStudent.Id).FirstOrDefault();
            student.Name = passedStudent.Name;
            student.Email = passedStudent.Email;
            student.Genderd = passedStudent.Genderd;
            if(passedStudent.studentImage != null)
            {
                if (!Directory.Exists(Server.MapPath("~/UploadFiles/StudentImage/")))
                {
                    Directory.CreateDirectory(Server.MapPath("~/UploadFiles/StudentImage/"));
                }

                string attachNumber = Guid.NewGuid().ToString();
                string InputFileName = Path.GetFileNameWithoutExtension(passedStudent.studentImage.FileName);
                string InputFileExtension = Path.GetExtension(passedStudent.studentImage.FileName);

                var severSavePath = Path.Combine(Server.MapPath("~/UploadFiles/StudentImage/")) + attachNumber + InputFileName + InputFileExtension;

                passedStudent.studentImage.SaveAs(severSavePath);

                student.Photo = attachNumber + InputFileName + InputFileExtension;

            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            Student student = db.Students.Where(std => std.Id == id).FirstOrDefault();
            List<StudentGrade> st = db.StudentGrades.Where(std => std.StudentId == id).ToList();

            foreach(var std in st)
            {
                var s = db.StudentGrades.Where(ss=>ss.StudentId == std.StudentId).FirstOrDefault();
                db.StudentGrades.Remove(s);
            }
           
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
       


    }
}

VSchool/Controllers/StudentsGradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VSchool.Models;

namespace VSchool.Controllers
{
    public class StudentsGradesController : Controller
    {
        TestEntities db = new TestEntities();

        // GET: StudentsGrades
        public ActionResult Index()
        {
           // List<StudentGrade> students = db.StudentGrades.ToList();
            return View();
        }

        public ActionResult SubmitDegree()
        {
            ViewBag.students = new SelectList(db.Students.ToList(), "Id", "Name");
            ViewBag.subjects = new SelectList(db.Subjects.ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult SubmitDegree(StudentGrade passedStudentGrade)
        {
            StudentGrade stdGrade = new StudentGrade();
            stdGrade.StudentId = passedStudentGrade.StudentId;
            stdGrade.SubjectId = passedStudentGrade.SubjectId;
            stdGrade.Degree = passedStudentGrade.Degree;
            db.StudentGrades.Add(stdGrade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult SearchDegree(string studentName, string subjectName)
        {
            List<StudentGrade> students = db.StudentGrades.Where(studentGrade => (studentGrade.Student.Name.Contains(studentName) || studentName == null || studentName == "") && (studentGrade.Subject.Name.Contains(subjectName) || subjectName == null || subjectName=="")).ToList();

            return View(students);

        }

        public ActionResult Edit(int id)
        {
            
            StudentGrade student = db.StudentGrades.Where(stdGrd => stdGrd.Id == id).FirstOrDefault();
            ViewBag.students = new SelectList(db.Students.ToList(), "Id", "Name", id);
            ViewBag.subjects = new SelectList(db.Subjects.ToList(), "Id", "Name", id);
            return View(student);
        }

        [HttpPost]
        public ActionResult Edit(StudentGrade passedStudentGrade)
        {
            StudentGrade student = db.StudentGrades.Where(stdGrd => stdGrd.Id == passedStudentGrade.Id).FirstOrDefault();
            student.StudentId = passedStudentGrade.StudentId;
            student.SubjectId = passedStudentGrade.SubjectId;
            student.Degree = passedStudentGrade.Degree;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int id)
        {
            StudentGrade stdGrade = db.StudentGrades.Where(studentGrade => studentGrade.Id == id).FirstOrDefault();
            db.StudentGrades.Remove(stdGrade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

VSchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VSchool</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VSchool", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                    <li>@Html.ActionLink("Students Grades", "Index", "StudentsGrades")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

        <div class="modal" tabindex="-1" role="dialog" id="my-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">

                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h3 class="modal-title"></h3>
                    </div>
                    <div class="modal-body">
                       
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>